# Generated by Django 5.1.3 on 2024-12-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('mech', models.IntegerField()),
                ('civil', models.IntegerField()),
                ('ee', models.IntegerField()),
                ('cse', models.IntegerField()),
            ],
            options={
                'db_table': 'student_data',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('admission_date', models.DateField()),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('EE', 'Electrical Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=5)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
