# Generated by Django 5.1.3 on 2024-12-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_attendencedata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendencedata',
            table='attendence_data',
        ),
    ]
